// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI operations (migrate, db push, generate) need a direct/session
    // connection — Supabase's transaction-mode pooler (DATABASE_URL) blocks
    // the prepared statements and DDL these commands rely on.
    url: process.env.DIRECT_URL,
  },
});
