/*
  Warnings:

  - You are about to drop the column `organizationId` on the `Workstation` table. All the data in the column will be lost.
  - Added the required column `siteId` to the `Workstation` table without a default value. This is not possible if the table is not empty.

*/
-- CreateEnum
CREATE TYPE "PlatformRole" AS ENUM ('SUPER_ADMIN', 'L3_SUPPORT', 'COMPANY_ADMIN', 'SITE_ADMIN');

-- DropIndex
DROP INDEX "Workstation_organizationId_idx";

-- AlterTable
ALTER TABLE "Workstation" DROP COLUMN "organizationId",
ADD COLUMN     "siteId" TEXT NOT NULL;

-- CreateTable
CREATE TABLE "Company" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Company_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Site" (
    "id" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "address" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Site_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PlatformUser" (
    "id" UUID NOT NULL,
    "role" "PlatformRole" NOT NULL,
    "companyId" TEXT,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PlatformUser_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SiteAssignment" (
    "id" TEXT NOT NULL,
    "userId" UUID NOT NULL,
    "siteId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SiteAssignment_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "Site_companyId_idx" ON "Site"("companyId");

-- CreateIndex
CREATE UNIQUE INDEX "PlatformUser_email_key" ON "PlatformUser"("email");

-- CreateIndex
CREATE INDEX "SiteAssignment_siteId_idx" ON "SiteAssignment"("siteId");

-- CreateIndex
CREATE UNIQUE INDEX "SiteAssignment_userId_siteId_key" ON "SiteAssignment"("userId", "siteId");

-- CreateIndex
CREATE INDEX "Workstation_siteId_idx" ON "Workstation"("siteId");

-- AddForeignKey
ALTER TABLE "Site" ADD CONSTRAINT "Site_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PlatformUser" ADD CONSTRAINT "PlatformUser_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SiteAssignment" ADD CONSTRAINT "SiteAssignment_userId_fkey" FOREIGN KEY ("userId") REFERENCES "PlatformUser"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SiteAssignment" ADD CONSTRAINT "SiteAssignment_siteId_fkey" FOREIGN KEY ("siteId") REFERENCES "Site"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Workstation" ADD CONSTRAINT "Workstation_siteId_fkey" FOREIGN KEY ("siteId") REFERENCES "Site"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
-- PlatformUser.id is not generated by Prisma: it is always the same UUID as
-- the corresponding auth.users row created via the invite-only provisioning
-- flow (never a public sign-up). Deleting the Supabase auth user removes the
-- platform_user row with it, so there is no way to end up with a dangling
-- account after an admin revokes access at the auth layer.
ALTER TABLE "PlatformUser" ADD CONSTRAINT "PlatformUser_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- CheckConstraint
-- Enforces the rule Prisma's schema language can't express: companyId is
-- required for company_admin/site_admin (their access is scoped to a
-- tenant) and forbidden for super_admin/l3_support (platform-level roles,
-- above any single tenant). Any role added later that isn't listed on
-- either side of this constraint will fail every insert/update until it's
-- explicitly classified here — fail closed, not silently permissive.
ALTER TABLE "PlatformUser" ADD CONSTRAINT "PlatformUser_role_companyId_check" CHECK (
  (role IN ('SUPER_ADMIN', 'L3_SUPPORT') AND "companyId" IS NULL) OR
  (role IN ('COMPANY_ADMIN', 'SITE_ADMIN') AND "companyId" IS NOT NULL)
);
