-- Migration D of 5: the risk core — Hazard catalog, RiskMatrixVersion/
-- RiskMatrixCell, RiskAssessment, RiskFinding, ExposureMeasurement — plus
-- seed data (system hazard catalog, the v1-generic-5x5 matrix and its
-- cells). RiskBand is reused from the existing enum (LOW/MODERATE/
-- ELEVATED/HIGH) rather than a second scale, so ergonomic scores and risk
-- findings speak one vocabulary.

-- CreateTable
CREATE TABLE "Hazard" (
    "id" TEXT NOT NULL,
    "companyId" TEXT,
    "category" "HazardCategory" NOT NULL,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "isSystem" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Hazard_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "Hazard_companyId_category_idx" ON "Hazard"("companyId", "category");

-- AddForeignKey
ALTER TABLE "Hazard" ADD CONSTRAINT "Hazard_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "Hazard" ENABLE ROW LEVEL SECURITY;

-- Seed: system hazard catalog (companyId = NULL, isSystem = true), one or
-- more credible rows per HazardCategory. Client companies can add their own
-- rows later with companyId set and isSystem = false.
INSERT INTO "Hazard" ("id", "companyId", "category", "code", "name", "description", "isSystem", "updatedAt") VALUES
  (gen_random_uuid()::text, NULL, 'PHYSICAL_MECHANICAL', 'MECH-01', 'Manual panel handling', 'Repeated manual handling of large/awkward panels or sheet stock, risk of crush or strike injury.', true, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, NULL, 'PHYSICAL_MECHANICAL', 'MECH-02', 'Unguarded moving machine parts', 'Nip points, rotating shafts, or blades on production machinery without adequate guarding.', true, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, NULL, 'NOISE', 'NOISE-01', 'Press-line noise exposure', 'Continuous or impulse noise from stamping/press lines, measured against the 87 dB(A) exposure limit value.', true, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, NULL, 'VIBRATION', 'VIB-01', 'Hand-arm vibration from power tools', 'Regular use of grinders, sanders, or impact wrenches transmitting vibration to the hand-arm system.', true, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, NULL, 'LIGHTING', 'LIGHT-01', 'Insufficient task lighting', 'Illuminance below the level required for fine visual work at the task location.', true, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, NULL, 'CLIMATE_THERMAL', 'THERM-01', 'Thermal load — hot process area', 'Sustained heat exposure near ovens, furnaces, or other hot process equipment.', true, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, NULL, 'CHEMICAL', 'CHEM-01', 'Adhesives and lacquers — solvent exposure', 'Inhalation/dermal exposure to solvent-based adhesives or lacquers during application or curing.', true, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, NULL, 'CHEMICAL', 'CHEM-02', 'Formaldehyde / resin vapour', 'Vapour release from resin-bonded board or composite processing.', true, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, NULL, 'DUST_PARTICULATE', 'DUST-01', 'Respirable dust', 'Wood, metal, or mineral dust generated by cutting, sanding, or grinding operations.', true, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, NULL, 'BIOLOGICAL', 'BIO-01', 'Bioaerosol exposure in damp storage areas', 'Mould or bacterial growth in poorly ventilated or damp storage/process areas.', true, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, NULL, 'ERGONOMIC_MSD', 'ERGO-01', 'Repetitive manual handling — musculoskeletal load', 'Sustained or repeated awkward posture, force, or repetition at a workstation or task.', true, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, NULL, 'PSYCHOSOCIAL', 'PSYCH-01', 'Shift-work load', 'Rotating or night shift patterns associated with elevated psychosocial and fatigue risk. Recorded at job/workstation level only — never per respondent (ERGO_COMPLIANCE_BY_DESIGN.md §3.12).', true, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, NULL, 'ELECTRICAL', 'ELEC-01', 'Exposed live electrical conductors', 'Damaged enclosures, panels, or cabling presenting a shock or arc-flash risk.', true, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, NULL, 'FIRE_EXPLOSION', 'FIRE-01', 'Dust-explosion risk (ATEX zone)', 'Combustible dust accumulation in a zone requiring ATEX-rated equipment and housekeeping controls.', true, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, NULL, 'RADIATION', 'RAD-01', 'Welding arc UV radiation', 'Ultraviolet radiation from arc welding processes, risk to unprotected skin and eyes.', true, CURRENT_TIMESTAMP);

-- CreateTable
CREATE TABLE "RiskMatrixVersion" (
    "version" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT false,
    "activatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RiskMatrixVersion_pkey" PRIMARY KEY ("version")
);

-- CreateIndex
-- Partial unique index: at most one row may have isActive = true. Prisma's
-- schema language can't express this (no filtered/partial index support),
-- so it's hand-added here — same pattern as
-- MethodologyVersion_isActive_unique_when_true.
CREATE UNIQUE INDEX "RiskMatrixVersion_isActive_unique_when_true" ON "RiskMatrixVersion"("isActive") WHERE "isActive" = true;

ALTER TABLE "RiskMatrixVersion" ENABLE ROW LEVEL SECURITY;

-- Seed: v1-generic-5x5, an independently-defined plain 5x5 probability x
-- severity matrix (ERGO_COMPLIANCE_BY_DESIGN.md §3.7's discipline applied
-- to risk matrices, not just ergonomic scoring — no INCDPM/Darabont-shaped
-- matrix seeded here, see the open §5 item on distributability).
INSERT INTO "RiskMatrixVersion" ("version", "label", "isActive", "activatedAt") VALUES
  ('v1-generic-5x5', 'Generic 5x5 probability x severity matrix (v1)', true, CURRENT_TIMESTAMP);

-- CreateTable
CREATE TABLE "RiskMatrixCell" (
    "id" TEXT NOT NULL,
    "matrixVersion" TEXT NOT NULL,
    "probability" INTEGER NOT NULL,
    "severity" INTEGER NOT NULL,
    "riskScore" INTEGER NOT NULL,
    "riskBand" "RiskBand" NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RiskMatrixCell_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "RiskMatrixCell_matrixVersion_probability_severity_key" ON "RiskMatrixCell"("matrixVersion", "probability", "severity");

-- CreateIndex
CREATE INDEX "RiskMatrixCell_matrixVersion_idx" ON "RiskMatrixCell"("matrixVersion");

-- AddForeignKey
ALTER TABLE "RiskMatrixCell" ADD CONSTRAINT "RiskMatrixCell_matrixVersion_fkey" FOREIGN KEY ("matrixVersion") REFERENCES "RiskMatrixVersion"("version") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "RiskMatrixCell" ENABLE ROW LEVEL SECURITY;

-- Seed: all 25 cells of the 5x5 matrix. riskScore = probability * severity
-- (classic product method). Bands: LOW <= 4, MODERATE 5-9, ELEVATED 10-14,
-- HIGH >= 15.
INSERT INTO "RiskMatrixCell" ("id", "matrixVersion", "probability", "severity", "riskScore", "riskBand") VALUES
  (gen_random_uuid()::text, 'v1-generic-5x5', 1, 1, 1, 'LOW'),
  (gen_random_uuid()::text, 'v1-generic-5x5', 1, 2, 2, 'LOW'),
  (gen_random_uuid()::text, 'v1-generic-5x5', 1, 3, 3, 'LOW'),
  (gen_random_uuid()::text, 'v1-generic-5x5', 1, 4, 4, 'LOW'),
  (gen_random_uuid()::text, 'v1-generic-5x5', 1, 5, 5, 'MODERATE'),
  (gen_random_uuid()::text, 'v1-generic-5x5', 2, 1, 2, 'LOW'),
  (gen_random_uuid()::text, 'v1-generic-5x5', 2, 2, 4, 'LOW'),
  (gen_random_uuid()::text, 'v1-generic-5x5', 2, 3, 6, 'MODERATE'),
  (gen_random_uuid()::text, 'v1-generic-5x5', 2, 4, 8, 'MODERATE'),
  (gen_random_uuid()::text, 'v1-generic-5x5', 2, 5, 10, 'ELEVATED'),
  (gen_random_uuid()::text, 'v1-generic-5x5', 3, 1, 3, 'LOW'),
  (gen_random_uuid()::text, 'v1-generic-5x5', 3, 2, 6, 'MODERATE'),
  (gen_random_uuid()::text, 'v1-generic-5x5', 3, 3, 9, 'MODERATE'),
  (gen_random_uuid()::text, 'v1-generic-5x5', 3, 4, 12, 'ELEVATED'),
  (gen_random_uuid()::text, 'v1-generic-5x5', 3, 5, 15, 'HIGH'),
  (gen_random_uuid()::text, 'v1-generic-5x5', 4, 1, 4, 'LOW'),
  (gen_random_uuid()::text, 'v1-generic-5x5', 4, 2, 8, 'MODERATE'),
  (gen_random_uuid()::text, 'v1-generic-5x5', 4, 3, 12, 'ELEVATED'),
  (gen_random_uuid()::text, 'v1-generic-5x5', 4, 4, 16, 'HIGH'),
  (gen_random_uuid()::text, 'v1-generic-5x5', 4, 5, 20, 'HIGH'),
  (gen_random_uuid()::text, 'v1-generic-5x5', 5, 1, 5, 'MODERATE'),
  (gen_random_uuid()::text, 'v1-generic-5x5', 5, 2, 10, 'ELEVATED'),
  (gen_random_uuid()::text, 'v1-generic-5x5', 5, 3, 15, 'HIGH'),
  (gen_random_uuid()::text, 'v1-generic-5x5', 5, 4, 20, 'HIGH'),
  (gen_random_uuid()::text, 'v1-generic-5x5', 5, 5, 25, 'HIGH');

-- CreateTable
-- Exactly one of workstationId / processId, enforced by a HAND-ADDED CHECK
-- constraint below (same technique as ManualInput_value_shape_check) —
-- Prisma's schema language can't express this.
CREATE TABLE "RiskAssessment" (
    "id" TEXT NOT NULL,
    "siteId" TEXT NOT NULL,
    "workstationId" TEXT,
    "processId" TEXT,
    "matrixVersion" TEXT NOT NULL,
    "status" "RiskAssessmentStatus" NOT NULL DEFAULT 'DRAFT',
    "assessorUserId" UUID NOT NULL,
    "approvedByUserId" UUID,
    "assessedAt" TIMESTAMP(3) NOT NULL,
    "approvedAt" TIMESTAMP(3),
    "pilotContext" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RiskAssessment_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "RiskAssessment_siteId_idx" ON "RiskAssessment"("siteId");

-- CreateIndex
CREATE INDEX "RiskAssessment_workstationId_idx" ON "RiskAssessment"("workstationId");

-- AddForeignKey
ALTER TABLE "RiskAssessment" ADD CONSTRAINT "RiskAssessment_siteId_fkey" FOREIGN KEY ("siteId") REFERENCES "Site"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RiskAssessment" ADD CONSTRAINT "RiskAssessment_workstationId_fkey" FOREIGN KEY ("workstationId") REFERENCES "Workstation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RiskAssessment" ADD CONSTRAINT "RiskAssessment_processId_fkey" FOREIGN KEY ("processId") REFERENCES "Process"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RiskAssessment" ADD CONSTRAINT "RiskAssessment_matrixVersion_fkey" FOREIGN KEY ("matrixVersion") REFERENCES "RiskMatrixVersion"("version") ON DELETE RESTRICT ON UPDATE CASCADE;

-- CheckConstraint
ALTER TABLE "RiskAssessment" ADD CONSTRAINT "RiskAssessment_exactly_one_subject_check" CHECK (
  ("workstationId" IS NOT NULL AND "processId" IS NULL) OR
  ("workstationId" IS NULL AND "processId" IS NOT NULL)
);

ALTER TABLE "RiskAssessment" ENABLE ROW LEVEL SECURITY;

-- CreateTable
CREATE TABLE "RiskFinding" (
    "id" TEXT NOT NULL,
    "riskAssessmentId" TEXT NOT NULL,
    "hazardId" TEXT NOT NULL,
    "probability" INTEGER NOT NULL,
    "severity" INTEGER NOT NULL,
    "riskScore" INTEGER NOT NULL,
    "riskBand" "RiskBand" NOT NULL,
    "existingControls" TEXT,
    "notes" TEXT,
    "residualProbability" INTEGER,
    "residualSeverity" INTEGER,
    "residualRiskScore" INTEGER,
    "residualRiskBand" "RiskBand",
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RiskFinding_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "RiskFinding_riskAssessmentId_idx" ON "RiskFinding"("riskAssessmentId");

-- AddForeignKey
ALTER TABLE "RiskFinding" ADD CONSTRAINT "RiskFinding_riskAssessmentId_fkey" FOREIGN KEY ("riskAssessmentId") REFERENCES "RiskAssessment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RiskFinding" ADD CONSTRAINT "RiskFinding_hazardId_fkey" FOREIGN KEY ("hazardId") REFERENCES "Hazard"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "RiskFinding" ENABLE ROW LEVEL SECURITY;

-- CreateTable
CREATE TABLE "ExposureMeasurement" (
    "id" TEXT NOT NULL,
    "riskFindingId" TEXT NOT NULL,
    "value" DOUBLE PRECISION NOT NULL,
    "unit" TEXT NOT NULL,
    "limitValue" DOUBLE PRECISION,
    "limitReference" TEXT,
    "instrument" TEXT,
    "method" TEXT,
    "measuredAt" TIMESTAMP(3) NOT NULL,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ExposureMeasurement_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "ExposureMeasurement_riskFindingId_idx" ON "ExposureMeasurement"("riskFindingId");

-- AddForeignKey
ALTER TABLE "ExposureMeasurement" ADD CONSTRAINT "ExposureMeasurement_riskFindingId_fkey" FOREIGN KEY ("riskFindingId") REFERENCES "RiskFinding"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "ExposureMeasurement" ENABLE ROW LEVEL SECURITY;
